version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      API_PORT: 4000
      API_HOST: 0.0.0.0
    ports:
      - "4000:4000"
    networks:
      - spec-gen

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    environment:
      VITE_API_BASE_URL: http://api:4000
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - spec-gen

networks:
  spec-gen:
    driver: bridge
