# Development Environment Configuration

metadata:
  name: spec-gen-dev
  description: Development environment for Spec Gen applications
  environment: development

# Stack configuration for development
stack:
  version: "3.9"

  services:
    api:
      build:
        context: ${GIT_ROOT}
        dockerfile: apps/api/Dockerfile
      environment:
        API_PORT: 4000
        API_HOST: 0.0.0.0
        NODE_ENV: development
      ports:
        - "4000:4000"
      networks:
        - spec-gen-dev
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      health_check:
        path: /health
        interval: 30s
        timeout: 10s
        retries: 3

    crm-client:
      build:
        context: ${GIT_ROOT}
        dockerfile: apps/crm-client/Dockerfile
      environment:
        VITE_API_BASE_URL: http://api:4000
        NODE_ENV: development
      ports:
        - "3000:80"
      depends_on:
        - api
      networks:
        - spec-gen-dev
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      health_check:
        path: /
        interval: 30s
        timeout: 10s
        retries: 3

  networks:
    spec-gen-dev:
      driver: bridge

# Development-specific settings
development:
  debug: true
  hot_reload: true
  log_level: debug

# Ingress configuration
ingress:
  host: dev.spec-gen.local
  paths:
    - path: /api
      service: api
      port: 4000
    - path: /
      service: crm-client
      port: 80

# Storage and secrets
storage:
  type: local
  path: /data/spec-gen-dev

secrets:
  - name: database_url
    source: dev-secrets
    key: DATABASE_URL
  - name: jwt_secret
    source: dev-secrets
    key: JWT_SECRET